######################################################################
# Automatically generated by qmake (2.01a) ? 9? 21 14:05:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
QT += xmlpatterns

# Input
HEADERS += queryhelper.h
SOURCES += main.cpp queryhelper.cpp
RESOURCES += qplanet.qrc
